custom_models:
- api_base: http://10.0.4.73:8000/v1
  api_key: ''
  custom_id: DeepSeek-R1-Distill-Qwen-32B-local
  name: DeepSeek-R1-Distill-Qwen-32B-local
- api_base: http://10.0.4.74:8000/v1
  api_key: ''
  custom_id: cwy/deepseek-llm-7b-chat-local-mYau
  name: cwy/deepseek-llm-7b-chat-local
device: cuda
embed_model: local/BAAI/bge-m3
enable_knowledge_base: true
enable_knowledge_graph: false
enable_reranker: false
enable_web_search: false
filename: saves/config/base.yaml
model_dir: /models
model_local_paths:
  BAAI/bge-m3: /app/src/data/BAAI/bge-m3
model_name: cwy/deepseek-llm-7b-chat-local-mYau
model_name_lite: Qwen/Qwen2.5-7B-Instruct
model_provider: custom
model_provider_lite: siliconflow
reranker: siliconflow/BAAI/bge-reranker-v2-m3
save_dir: saves
stream: true
use_rewrite_query: 'off'
valuable_model_provider:
- deepseek
- siliconflow
